"""Seed accounts and the demo bookings a reviewer can click."""

from app.domain import AccountSnapshot, Booking

ACCOUNTS: list[AccountSnapshot] = [
    AccountSnapshot(
        account_number="9A4K2M",
        name="Mehta Textiles",
        status="open",
        inbound_policy="deny_third_party",
        exception_shippers=[],
        known_third_parties=[],
        linked_user_ids=["mehta.ops"],
        ship_from_postals=["400001"],
        destination_countries=["IN"],
        usual_services=["ground"],
        mostly_domestic_ground=True,
        weekly_pace=6,
        median_weight_kg=8,
        shipment_count_90d=80,
    ),
    AccountSnapshot(
        account_number="2LX8QP",
        name="Northwind Exports",
        status="open",
        inbound_policy="allow",
        exception_shippers=["SHIP99"],
        known_third_parties=["SHIP99"],
        linked_user_ids=["northwind.ops"],
        ship_from_postals=["110001", "110020"],
        destination_countries=["US", "GB", "AE", "IN"],
        usual_services=["express", "international"],
        mostly_domestic_ground=False,
        weekly_pace=20,
        median_weight_kg=12,
        shipment_count_90d=220,
    ),
    AccountSnapshot(
        account_number="7C0SED",
        name="Retired Traders",
        status="closed",
        inbound_policy="deny_third_party",
        linked_user_ids=["retired.ops"],
        ship_from_postals=["600001"],
        destination_countries=["IN"],
        usual_services=["ground"],
        mostly_domestic_ground=True,
        weekly_pace=2,
        median_weight_kg=6,
        shipment_count_90d=40,
    ),
    AccountSnapshot(
        account_number="4NEW8K",
        name="New Boutique",
        status="open",
        inbound_policy="allow",
        linked_user_ids=["new.owner"],
        ship_from_postals=["560001"],
        destination_countries=["IN"],
        usual_services=["ground"],
        mostly_domestic_ground=True,
        weekly_pace=1,
        median_weight_kg=3,
        shipment_count_90d=2,
    ),
    AccountSnapshot(
        account_number="5RUSH3",
        name="Quiet Books",
        status="open",
        inbound_policy="allow",
        linked_user_ids=["rush.ops"],
        ship_from_postals=["411001"],
        destination_countries=["IN"],
        usual_services=["ground"],
        mostly_domestic_ground=True,
        weekly_pace=3,
        median_weight_kg=5,
        shipment_count_90d=40,
    ),
    AccountSnapshot(
        account_number="6LIGHT2",
        name="Parcel Hub",
        status="open",
        inbound_policy="allow",
        linked_user_ids=["parcel.ops"],
        ship_from_postals=["500001"],
        destination_countries=["IN"],
        usual_services=["ground"],
        mostly_domestic_ground=True,
        weekly_pace=10,
        median_weight_kg=1.5,
        shipment_count_90d=70,
    ),
]

# Quiet Books is seeded with this many attempts already in the last hour.
RUSH_RECENT_1H = 8


def _booking(**kwargs) -> dict:
    base = dict(
        channel="web_single_page",
        guest=False,
        payment_type="bill_shipper",
        shipper_account=None,
        ship_from_country="IN",
        ship_to_country="IN",
        service="ground",
        package_count=1,
        packaging="customer",
        declared_value=None,
    )
    base.update(kwargs)
    return base


SCENARIOS = [
    {
        "id": "normal",
        "label": "Normal ground",
        "expect": "allow",
        "blurb": "Mehta Textiles, usual Mumbai origin, usual weight, the owner is logged in.",
        "booking": _booking(
            ups_user_id="mehta.ops",
            billed_account="9A4K2M",
            shipper_account="9A4K2M",
            ship_from_postal="400001",
            ship_to_postal="380001",
            weight_kg=7.5,
            service="ground",
        ),
    },
    {
        "id": "guest",
        "label": "Guest uses an account",
        "expect": "step-up",
        "blurb": "A guest types Mehta’s account number. The login is not linked to that account.",
        "booking": _booking(
            guest=True,
            ups_user_id=None,
            billed_account="9A4K2M",
            shipper_account="9A4K2M",
            ship_from_postal="400001",
            ship_to_postal="380001",
            weight_kg=7,
            service="ground",
        ),
    },
    {
        "id": "deny",
        "label": "Third party on a deny-list",
        "expect": "block",
        "blurb": "Mehta Textiles refuses third-party billing. SHIPX1 is not on the exception list.",
        "booking": _booking(
            guest=True,
            ups_user_id=None,
            payment_type="bill_third_party",
            billed_account="9A4K2M",
            shipper_account="SHIPX1",
            ship_from_postal="560001",
            ship_to_postal="400001",
            weight_kg=9,
            service="ground",
        ),
    },
    {
        "id": "partner",
        "label": "Known third party",
        "expect": "allow",
        "blurb": "Northwind allows SHIP99. Origin and service match that account’s history.",
        "booking": _booking(
            ups_user_id="northwind.ops",
            payment_type="bill_third_party",
            billed_account="2LX8QP",
            shipper_account="SHIP99",
            ship_from_postal="110001",
            ship_to_postal="10001",
            ship_to_country="US",
            weight_kg=11,
            service="international",
        ),
    },
    {
        "id": "new_payer",
        "label": "New payer, new origin",
        "expect": "hold",
        "blurb": "A shipper Northwind has never seen bills them from outside their footprint.",
        "booking": _booking(
            guest=True,
            ups_user_id=None,
            payment_type="bill_third_party",
            billed_account="2LX8QP",
            shipper_account="NEWSH1",
            ship_from_postal="400070",
            ship_to_postal="10001",
            ship_to_country="US",
            weight_kg=10,
            service="international",
        ),
    },
    {
        "id": "lane",
        "label": "New international lane",
        "expect": "hold",
        "blurb": "Mehta normally ships domestic ground. This one is international, from a new postal code.",
        "booking": _booking(
            ups_user_id="mehta.ops",
            billed_account="9A4K2M",
            shipper_account="9A4K2M",
            ship_from_postal="560001",
            ship_to_postal="10001",
            ship_to_country="US",
            weight_kg=8,
            service="international",
        ),
    },
    {
        "id": "velocity",
        "label": "Burst of bookings",
        "expect": "hold",
        "blurb": "Quiet Books ships about three times a week. Eight attempts are already in the last hour.",
        "booking": _booking(
            ups_user_id="rush.ops",
            billed_account="5RUSH3",
            shipper_account="5RUSH3",
            ship_from_postal="411001",
            ship_to_postal="400001",
            weight_kg=4.5,
            service="ground",
        ),
    },
    {
        "id": "closed",
        "label": "Closed account",
        "expect": "block",
        "blurb": "Retired Traders is closed. The account cannot pay.",
        "booking": _booking(
            guest=True,
            ups_user_id=None,
            billed_account="7C0SED",
            shipper_account="7C0SED",
            ship_from_postal="600001",
            ship_to_postal="400001",
            weight_kg=6,
            service="ground",
        ),
    },
    {
        "id": "thin",
        "label": "New account",
        "expect": "step-up",
        "blurb": "New Boutique has two shipments in 90 days. Thin history is a step-up, not a block.",
        "booking": _booking(
            ups_user_id="new.owner",
            billed_account="4NEW8K",
            shipper_account="4NEW8K",
            ship_from_postal="560001",
            ship_to_postal="400001",
            weight_kg=3,
            service="ground",
        ),
    },
    {
        "id": "heavy",
        "label": "Unexpected weight",
        "expect": "hold",
        "blurb": "Parcel Hub’s usual parcel is 1.5 kg. Rules pass. The model holds a 28 kg carton for a person.",
        "booking": _booking(
            ups_user_id="parcel.ops",
            billed_account="6LIGHT2",
            shipper_account="6LIGHT2",
            ship_from_postal="500001",
            ship_to_postal="400001",
            weight_kg=28,
            service="ground",
        ),
    },
    {
        "id": "card",
        "label": "Card payment",
        "expect": "allow",
        "blurb": "Card payments are outside this check. The loss we are scoring is account billing.",
        "booking": _booking(
            guest=True,
            ups_user_id=None,
            payment_type="card",
            billed_account=None,
            shipper_account=None,
            ship_from_postal="400001",
            ship_to_postal="560001",
            weight_kg=2,
            service="ground",
        ),
    },
]


def account_map() -> dict[str, AccountSnapshot]:
    return {account.account_number: account for account in ACCOUNTS}


def booking_from_payload(payload: dict) -> Booking:
    return Booking(
        payment_type=payload["payment_type"],
        ship_from_postal=str(payload["ship_from_postal"]),
        ship_from_country=payload.get("ship_from_country") or "IN",
        ship_to_postal=str(payload["ship_to_postal"]),
        ship_to_country=payload.get("ship_to_country") or "IN",
        weight_kg=float(payload["weight_kg"]),
        service=payload["service"],
        guest=bool(payload.get("guest")),
        ups_user_id=payload.get("ups_user_id"),
        billed_account=payload.get("billed_account"),
        shipper_account=payload.get("shipper_account"),
        channel=payload.get("channel") or "web_single_page",
        package_count=int(payload.get("package_count") or 1),
        packaging=payload.get("packaging") or "customer",
        declared_value=payload.get("declared_value"),
        tx_id=payload.get("tx_id"),
    )
